"""empty message

Revision ID: 068cc3dc8c21
Revises: a4ead4b5a78b
Create Date: 2021-03-26 01:39:45.783016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068cc3dc8c21'
down_revision = 'a4ead4b5a78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'time')
    # ### end Alembic commands ###
