"""empty message

Revision ID: 0adc2edc207a
Revises: 068cc3dc8c21
Create Date: 2021-03-29 17:40:47.470110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0adc2edc207a'
down_revision = '068cc3dc8c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subway_passenger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('holiday', sa.Boolean(), nullable=False),
    sa.Column('insub', sa.Integer(), nullable=False),
    sa.Column('outsub', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subway_passenger')
    # ### end Alembic commands ###
