"""empty message

Revision ID: 4705dce0a73f
Revises: be3956f26b93
Create Date: 2021-03-30 15:13:34.484167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4705dce0a73f'
down_revision = 'be3956f26b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MLModel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('chat', 'text',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'text',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_table('MLModel')
    # ### end Alembic commands ###
